# Generated by Django 3.0.2 on 2020-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('aboutme', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('created', models.DateTimeField(auto_now=True)),
                ('font_size', models.IntegerField(null=True)),
            ],
        ),
    ]
