# Generated by Django 3.0.2 on 2020-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('aboutme', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='u_dashboard',
        ),
    ]
