# Generated by Django 3.0.2 on 2020-04-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0003_auto_20200427_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdash',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
