# Generated by Django 3.0.2 on 2020-04-28 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0004_userdash_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdash',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
