# Generated by Django 3.0.2 on 2020-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0005_userdash_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdash',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
