# Generated by Django 3.0.2 on 2020-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0008_userdash_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdash',
            name='font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
