# Generated by Django 3.0.2 on 2020-05-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0008_auto_20200501_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdash',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdash',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdash',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdash',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
