# Generated by Django 3.0.2 on 2020-04-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecards', '0009_auto_20200428_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdash',
            name='font_size',
            field=models.IntegerField(null=True),
        ),
    ]
